# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ff28a396bb7a94d335d70f06a590ce72ae9b5237099f1c52c4a27f1e4c90040a9942b18aad3c5231ecaa106ca3e993fb68e13c5396e8cf4135c1ac80bcef14b

test:
  secret_key_base: 427a265ac2dd7f5f9b7a67fdeae8dd6dbe5a6e199dc02699ab233b24525e056d8e2fdcf55bec7e1a262d63c48ccfe76198512d6e9a558aca84d077138ec8d182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
